### ISSUE TITLE
couldn't run grunt server the first time

### ISSUE THREAD

**Issue by richpav** [codio/tutorial_yo_angular#2]
I had to do this first:

gem update --system && gem install compass

I was on this page in the tutorial:

Running & Previewing the App

**Comment by ghost** [comment]
@richpav 
When on the step `Use a Generator to scaffold your App` did you select 'Y' to include use Sass (with Compass) ? 
If selecting 'N' this shouldn't be required.

**Comment by richpav** [comment]
Whether or not to install the Sassified verison wasn't mentioned so I selected Y.

**Comment by ghost** [comment]
> > The AngularJS generator provides options to include use Sass (with Compass) and/or Bootstrap. Enter ‘n’ and ‘y’ respectively to these options.
